In [1]:
import numpy as np

## DataType & Attribute

In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [6]:
a1.size

3

In [7]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2,3],
               [4,5,6]])

In [9]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a2.shape

(2, 3)

In [13]:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [15,17,18]]])

In [14]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [15, 17, 18]]])

In [15]:
a3.shape

(2, 3, 3)

In [19]:
a3[1][2]

array([15, 17, 18])

In [20]:
ones = np.ones((2,3))

In [21]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.random.random((2,3))

array([[0.44707579, 0.17028051, 0.28980184],
       [0.36054616, 0.7834902 , 0.19798226]])

In [25]:
np.random.randint(0,3,(3,3,3))

array([[[0, 1, 0],
        [0, 2, 1],
        [2, 1, 0]],

       [[0, 0, 2],
        [0, 2, 1],
        [1, 2, 0]],

       [[0, 1, 2],
        [2, 0, 2],
        [2, 0, 2]]])

In [26]:
np.arange(0,10,.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [28]:

np.random.randint(0,3,(2,3))

array([[1, 2, 1],
       [0, 1, 2]])

In [70]:
np.random.seed(7)
npar = np.random.random((5,3))

In [71]:
npar

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [63]:
np.random.seed(7)
a4 = np.random.randint(0,10,(3,4))
a4

array([[4, 9, 6, 3],
       [3, 7, 7, 9],
       [7, 8, 9, 8]])

In [74]:
np.random.shuffle(a4)

#### 

In [75]:
a4

array([[4, 9, 6, 3],
       [3, 7, 7, 9],
       [7, 8, 9, 8]])

## Viewing arrays and matrices

In [76]:
np.unique(a4)

array([3, 4, 6, 7, 8, 9])

In [77]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [15, 17, 18]]])

In [78]:
a3[:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [15, 17, 18]]])

In [80]:
a3[:2, :2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [81]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [82]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [15, 17, 18]]])

In [83]:
a3[:1]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [84]:
a3[:1, :2]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [96]:
a3[:1, :3, :1]

array([[[1],
        [4],
        [7]]])

##### 

In [99]:
a5 = np.random.randint(0,10,(2,3,4,5))

In [100]:
a5

array([[[[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]],

        [[1, 1, 5, 3, 2],
         [0, 4, 8, 7, 1],
         [4, 9, 3, 6, 7],
         [1, 0, 2, 7, 0]],

        [[0, 9, 8, 2, 0],
         [5, 5, 0, 9, 0],
         [8, 4, 5, 1, 4],
         [0, 7, 2, 0, 3]]],


       [[[9, 8, 3, 7, 1],
         [0, 1, 4, 6, 1],
         [0, 1, 0, 1, 8],
         [4, 1, 6, 8, 5]],

        [[2, 4, 7, 4, 1],
         [2, 8, 5, 2, 9],
         [6, 2, 5, 7, 7],
         [5, 5, 6, 0, 6]],

        [[4, 6, 2, 6, 8],
         [7, 0, 5, 8, 9],
         [7, 7, 6, 2, 5],
         [6, 1, 9, 3, 4]]]])

In [101]:
a5.shape

(2, 3, 4, 5)

In [102]:
a5[:, :, :, :4]

array([[[[0, 5, 7, 1],
         [4, 9, 0, 2],
         [7, 6, 2, 9],
         [5, 1, 0, 0]],

        [[1, 1, 5, 3],
         [0, 4, 8, 7],
         [4, 9, 3, 6],
         [1, 0, 2, 7]],

        [[0, 9, 8, 2],
         [5, 5, 0, 9],
         [8, 4, 5, 1],
         [0, 7, 2, 0]]],


       [[[9, 8, 3, 7],
         [0, 1, 4, 6],
         [0, 1, 0, 1],
         [4, 1, 6, 8]],

        [[2, 4, 7, 4],
         [2, 8, 5, 2],
         [6, 2, 5, 7],
         [5, 5, 6, 0]],

        [[4, 6, 2, 6],
         [7, 0, 5, 8],
         [7, 7, 6, 2],
         [6, 1, 9, 3]]]])

In [103]:
5%3

2

In [104]:
1%2

1

In [105]:
1%3

1