In [1]:
import pandas as pd
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])

In [3]:
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a1.shape

(3,)

In [6]:
a2 = np.array([[1,2,3],
               [4,5,6]])

In [7]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a2.shape

(2, 3)

In [9]:
crar = np.random.randint(0,20,(2,3,3))

In [10]:
crar

array([[[17,  7,  2],
        [ 6, 18, 13],
        [12,  1,  9]],

       [[10, 19, 14],
        [16, 13,  1],
        [10,  1,  5]]])

In [14]:
crar1 = np.random.random((3,2,2,2))

In [15]:
crar1

array([[[[0.0568066 , 0.38521125],
         [0.46412704, 0.69970468]],

        [[0.76973487, 0.16627731],
         [0.13501852, 0.25892355]]],


       [[[0.89651514, 0.19719994],
         [0.64197349, 0.47631225]],

        [[0.26994836, 0.10718435],
         [0.33171791, 0.9795007 ]]],


       [[[0.80966129, 0.8034391 ],
         [0.71119944, 0.42223663]],

        [[0.31539165, 0.79592515],
         [0.42027266, 0.04928338]]]])

In [17]:
crar1[:, :1, :1, :]

array([[[[0.0568066 , 0.38521125]]],


       [[[0.89651514, 0.19719994]]],


       [[[0.80966129, 0.8034391 ]]]])

In [18]:
shop = np.random.randint(0,12,size=(5,3))
shop

array([[ 7,  1,  2],
       [ 7, 11,  8],
       [ 3,  3,  6],
       [10,  7,  5],
       [ 0,  1,  4]])

In [20]:
price = np.array([[28],
               [36],
               [77]])

In [22]:
price.shape, shop.shape

((3, 1), (5, 3))

In [32]:
weekly_sales = pd.DataFrame(shop,index=["Mon","Tue","Wedn","Thu","Fri"],
                                 columns=["Almond butter","Peanut butter","Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               7              1              2
Tue               7             11              8
Wedn              3              3              6
Thu              10              7              5
Fri               0              1              4

In [26]:
price_df = pd.DataFrame(price,index=["Almond butter","Peanut butter","Cashew butter"],
                              columns=["Price"])
price_df

Price
Almond butter     28
Peanut butter     36
Cashew butter     77

In [28]:
total = np.dot(shop,price)

In [29]:
total

array([[ 386],
       [1208],
       [ 654],
       [ 917],
       [ 344]])

In [30]:
weekly_sales["total"] = total

In [31]:
weekly_sales

Almond butter  Peanut butter  Cashew butter  total
Mon              7              1              2    386
Tue              7             11              8   1208
Wen              3              3              6    654
Thu             10              7              5    917
Fra              0              1              4    344

In [33]:
price_df.describe()

Price
count   3.000000
mean   47.000000
std    26.286879
min    28.000000
25%    32.000000
50%    36.000000
75%    56.500000
max    77.000000

In [34]:
weekly_sales.describe()

Almond butter  Peanut butter  Cashew butter
count       5.000000       5.000000       5.000000
mean        5.400000       4.600000       5.000000
std         3.911521       4.335897       2.236068
min         0.000000       1.000000       2.000000
25%         3.000000       1.000000       4.000000
50%         7.000000       3.000000       5.000000
75%         7.000000       7.000000       6.000000
max        10.000000      11.000000       8.000000

In [40]:
weekly_sales["Almond butter"] = weekly_sales["Almond butter"].str.to_replace('['\.']','').astype(int)

SyntaxError: unexpected character after line continuation character (<ipython-input-40-0f582275bd8a>, line 1)

In [42]:
weekly_sales.groupby("Almond butter").mean()

Peanut butter  Cashew butter
Almond butter                              
0                          1              4
3                          3              6
7                          6              5
10                         7              5

In [43]:
rarr

NameError: name 'rarr' is not defined

In [44]:
ran_arr = np.random.randint(0,9,size=(3,4))

In [45]:
ran_arr

array([[3, 2, 1, 6],
       [2, 3, 8, 8],
       [6, 2, 2, 1]])

In [46]:
np.sort(ran_arr)

array([[1, 2, 3, 6],
       [2, 3, 8, 8],
       [1, 2, 2, 6]])

In [47]:
np.argsort(ran_arr)# sort qilingan elementlar aslidagi joylashuvini ko'rsatadi

array([[2, 1, 0, 3],
       [0, 1, 2, 3],
       [3, 1, 2, 0]], dtype=int64)

In [48]:
np.sort(ran_arr) == np.argsort(ran_arr)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [49]:
ran_arr

array([[3, 2, 1, 6],
       [2, 3, 8, 8],
       [6, 2, 2, 1]])

In [54]:
np.argmin(ran_arr)

2

In [56]:
bbb = np.random.randint(10,16,size=(4,3))

In [57]:
bbb

array([[14, 13, 10],
       [12, 10, 13],
       [12, 13, 10],
       [13, 13, 11]])

In [61]:
np.sort(bbb), np.argsort(bbb), np.argmax(bbb,axis=0)

(array([[10, 13, 14],
        [10, 12, 13],
        [10, 12, 13],
        [11, 13, 13]]),
 array([[2, 1, 0],
        [1, 0, 2],
        [2, 0, 1],
        [2, 0, 1]], dtype=int64),
 array([0, 0, 1], dtype=int64))

In [62]:
np.argmax(bbb, axis=0)# demak axis=0 degani matrisani ustunlari boyicha

array([0, 0, 1], dtype=int64)

In [63]:
np.argmax(bbb,axis=1)# axis=1 esa matrisani qatorlari buyicha maksimumning indexi

array([0, 2, 1, 0], dtype=int64)

In [64]:
np.argmax(bbb,axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [65]:
bbb.shape

(4, 3)

## NumPy in Action!!!

In [1]:
<img src="panda.png"/>

SyntaxError: invalid syntax (<ipython-input-1-2ffd334afd26>, line 1)

In [2]:
<img src="car-photo.png"/>


SyntaxError: invalid syntax (<ipython-input-2-3a388c12618b>, line 1)